# Generated by Django 2.1.5 on 2019-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
