# Generated by Django 2.1.5 on 2019-03-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
