# Generated by Django 2.1.5 on 2019-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0002_home_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
