# Generated by Django 2.1.5 on 2019-03-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0003_home_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/worker/')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
