# Generated by Django 2.1.5 on 2019-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0004_auto_20190324_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='disc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
