# Generated by Django 2.1.5 on 2019-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0005_auto_20190324_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
