# Generated by Django 2.1.5 on 2019-04-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0007_auto_20190428_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='furniapp.Category'),
        ),
    ]
