# Generated by Django 2.1.5 on 2019-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0010_remove_home_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
