# Generated by Django 2.1.5 on 2019-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0011_auto_20190502_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='slug',
        ),
        migrations.AddField(
            model_name='worker',
            name='cw',
            field=models.IntegerField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='ex',
            field=models.IntegerField(default=65, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/worker/'),
        ),
    ]
