# Generated by Django 2.1.5 on 2019-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0012_auto_20190625_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
