# Generated by Django 2.1.5 on 2019-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0014_auto_20190625_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
