# Generated by Django 2.1.5 on 2019-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0015_auto_20190625_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
