# Generated by Django 2.1.5 on 2019-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0020_auto_20190625_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='Experience',
            field=models.IntegerField(default=5, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(default=45, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='mobile',
            field=models.PositiveIntegerField(default=55),
            preserve_default=False,
        ),
    ]
